services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Tests\helpers\:
        resource: '../tests/helpers/'

    Stripe\HttpClient\ClientInterface:
        alias: App\Tests\helpers\Service\Stripe\TestStripeHttpClient

    Stripe\HttpClient\StreamingClientInterface:
        alias: App\Tests\helpers\Service\Stripe\TestStripeHttpClient

    Symfony\Component\EventDispatcher\EventDispatcherInterface:
        alias: App\Tests\helpers\EventDispatcher\TestEventDispatcher
